apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: interceptor
    httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
    keda.sh/addon: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-interceptor
    app.kubernetes.io/name: {{ .Chart.Name }}-interceptor
    app.kubernetes.io/version: {{ .Values.images.tag | default .Chart.AppVersion }}
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ tpl .Values.additionalLabels . | indent 4}}
  name: {{ .Chart.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: interceptor
      httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
      keda.sh/addon: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        control-plane: interceptor
        httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
        keda.sh/addon: {{ .Chart.Name }}
        app: {{ .Chart.Name }}
        name: {{ .Chart.Name }}-interceptor
        app.kubernetes.io/name: {{ .Chart.Name }}-interceptor
        app.kubernetes.io/version: {{ .Values.images.tag | default .Chart.AppVersion }}
        app.kubernetes.io/component: interceptor
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{ tpl .Values.additionalLabels . | indent 4}}
    spec:
      containers:
      - args:
        image: "{{ .Values.images.interceptor }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.interceptor.pullPolicy | default "Always" }}
        name: {{ .Chart.Name }}-interceptor
        env:
        - name: KEDA_HTTP_OPERATOR_SERVICE_NAME
          value: "{{ .Chart.Name }}-{{ .Values.operator.adminService }}"
        - name: KEDA_HTTP_OPERATOR_SERVICE_PORT
          value: {{ .Values.operator.adminPort }}
        - name: KEDA_HTTP_OPERATOR_ROUTING_TABLE_PATH
          value: {{ .Values.operator.routingTableURLPath }}
        - name: KEDA_HTTP_OPERATOR_ROUTING_TABLE_UPDATE_DURATION_MS
          value: {{ .Values.interceptor.routingTableUpdateDurationMS }}
        - name: KEDA_HTTP_CURRENT_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: KEDA_HTTP_PROXY_PORT
          value: {{ .Values.interceptor.proxyPort }}
        - name: KEDA_HTTP_ADMIN_PORT
          value: {{ .Values.interceptor.adminPort }}
        - name: KEDA_HTTP_CONNECT_TIMEOUT
          value: {{ .Values.interceptor.tcpConnectTimeout }}
        - name: KEDA_HTTP_KEEP_ALIVE
          value: {{ .Values.interceptor.keepAlive }}
        - name: KEDA_RESPONSE_HEADER_TIMEOUT
          value: {{ .Values.interceptor.responseHeaderTimeout }}
        - name: KEDA_CONDITION_WAIT_TIMEOUT
          value: {{ .Values.interceptor.replicasWaitTimeout }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
