additionalLabels: ""

crds:
  install: true

operator:
  pullPolicy: Always
  resources:
    limits:
      cpu: 0.5
      memory: 64Mi
    requests:
      cpu: 250m
      memory: 20Mi
  port: 8443
  adminService: operator-admin
  adminPort: 9090
  routingTableURLPath: routing

scaler:
  service: external-scaler
  pullPolicy: Always
  grpcPort: 9090
  healthPort: 9091

interceptor:
  pullPolicy: Always
  adminService: interceptor-admin
  adminPort: 9090
  proxyService: interceptor-proxy
  proxyPort: 8080
  routingTableUpdateDurationMS: 500
  tcpConnectTimeout: 500ms
  keepAlive: 1s
  responseHeaderTimeout: 500ms
  replicasWaitTimeout: 1500ms

images:
  tag:
  operator: ghcr.io/kedacore/http-add-on-operator
  interceptor: ghcr.io/kedacore/http-add-on-interceptor
  scaler: ghcr.io/kedacore/http-add-on-scaler
